# Generated by Django 4.1.4 on 2023-01-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to='profile_pics'),
        ),
    ]
