# Generated by Django 4.1.4 on 2023-01-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0008_post_likes_post_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to='post_gifs'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
