# Generated by Django 4.1.4 on 2023-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0010_post_gif_url_post_image_url_post_video_thumbnail_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gif',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post_files'),
        ),
    ]
