# Generated by Django 4.1.4 on 2023-01-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0011_remove_post_gif_remove_post_image_post_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gif_url',
            new_name='file_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_thumbnail_url',
        ),
    ]
