# Generated by Django 4.1.4 on 2023-01-29 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0013_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
