# Generated by Django 4.1.4 on 2023-02-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0015_comment_comments_comment_downvotes_comment_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=models.ManyToManyField(blank=True, to='gorl.comment'),
        ),
    ]
