# Generated by Django 4.1.4 on 2023-02-15 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gorl', '0016_alter_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gorl.comment'),
        ),
    ]
